### ISSUE TITLE
typo - Operational Management - Stream A 

### ISSUE THREAD

**Issue by aramhovsepyan** [owaspsamm/core#107]
There is a typo in the word decommissioning (2m and 2s).

**Comment by shikida** [comment]
where?

https://owaspsamm.org/model/operations/operational-management/stream-b/
https://owaspsamm.org/model/operations/operational-management/

both look fine

**Comment by Pat-Duarte** [comment]
O-OM-2-B
Benefit
Standardized decommisioning process decreasing the risk of forgetting components
