### ISSUE TITLE
I think answer set S.yml is not used anywhere

### ISSUE THREAD

**Issue by BackNot** [owaspsamm/core#132]
Hi, 

Unless I am missing something or it is done on purpose, I think that this answer set is not used anywhere and it should be deleted. I tried looking for this ID but there are no questions linked to it. https://github.com/owaspsamm/core/blob/e01ec53ecb508f9760ff7b42926370fd2ade4290/model/answer_sets/S.yml

**Comment by 23bartman** [comment]
Good catch. We are removing the file from the repo. The PR has been created and it should be part of the new release.
