### ISSUE TITLE
Activity G-EG-1-A: Clarify wording of Qualifying Criteria

### ISSUE THREAD

**Issue by johndileo** [owaspsamm/core#145]
As discussed at the Belgium Summit, the Qualifying Criteria for Activity 1-A under the Education and Guidance Practice specify that training must have been "updated" within the last 12 months, when it's possible no updates were actually required.

Revise the language of the Activity's Qualifying Criteria, to indicate the content must have been *reviewed* within the last 12 months, and updated if required.

**Comment by johndileo** [comment]
I've updated the wording of that Qualifying Criterion to: "You have reviewed the training content within the last 12 months, and have completed any required updates"

While I was there, I also clarified and expanded the language of the last Qualifying Criterion, adding another Criterion that specifically addresses the initial/refresher training requirement for existing staff, either when the training content is updated or after 24 months since their last training.

**Comment by dkefer** [comment]
Has been fixed with https://github.com/owaspsamm/core/pull/146
