### ISSUE TITLE
Inclusion of the Not Applicable option in SAMM Responses

### ISSUE THREAD

**Issue by mufambisi** [owaspsamm/core#16]
I think we should have a Not Applicable answer in the template. There are some sections or practices that do not apply to some organizations or teams. An example is Supplier Security under Security Requirements practice. This practice is only applicable if organizations use software that is developed by a vendor not subject to the organizations practices. 

I recently did an assessment and i had to fudge this because it was not applicable and I did not want it to impact the overall score. I would imagine some other organizations would have the same issues for other areas.

Happy to discuss.

**Comment by dkefer** [comment]
Thank you for the issue!

We've discussed this issue during the core team meeting today. We've agreed that it makes sense to take this topic for further discussion to the next summit.

**Comment by aramhovsepyan** [comment]
Here is a blog where the core team expressed their opinion related to the Not Applicable option.
https://owaspsamm.org/blog/2023/02/28/the-not-applicable-question/
