### ISSUE TITLE
Rating in Excel assessment not updating on Mac and Online Versions

### ISSUE THREAD

**Issue by marc-on-github** [owaspsamm/core#161]
Hello,

I've encountered a problem with the OWASP SAMM Excel Assessment tool that might affect other users as well. The tool works fine on a Windows system, but there are issues when using it on macOS and in the online version of Excel (Office 365).

**Problem:**

- On macOS and in the online version of Excel, the rating in the assessment tool does not update even when all the inputs are correctly entered.
- The tool works as expected on a Windows system, where the ratings are updated accordingly.

**Steps to Reproduce:**

1. Download the OWASP SAMM Assessment tool and open it on a Mac or in the online version of Excel.
2. Perform the assessment and input the required data into the appropriate fields.
3. Notice that the rating does not automatically update.

**Expected Behavior:**

The rating should automatically update regardless of the operating system or Excel version being used, once the data is entered.

**Actual Behavior:**

On macOS and in the online version of Excel, the rating remains unchanged even after the data is inputted.

**Comment by SebaDele** [comment]
Hello Marc,
Thank you for raising this issue.
Can you let us know what language setting you have and use on your system?
We recently fixed an issue with formulas that did not update in languages other than English.

Can you check if you have the same issue with this version:
https://github.com/owaspsamm/toolbox-spreadsheet/blob/main/resources/SAMM_spreadsheet.xlsx

thank you
Seba

**Comment by johnellingsworth** [comment]
@marc-on-github  

I tested on OSX and did not encounter functional issues with the desktop version; the web version has some quirks with formatting - font changing to bold & italic - but functionality it worked as expected. 

Any chance you can share screenshots, or a screen recording? It will provide better context.

**Comment by maximbaele** [comment]
Please reopen if this behavior is still present on the latest version

**Comment by geoff-carve-systems** [comment]
I encountered a similar issue with the OWASP SAMM Excel Assessment made available as part of release v2.1.0 [here](https://github.com/owaspsamm/core/releases/download/v2.1.0/SAMM_spreadsheet.xlsx). It appears that there is a formula error (or a series of formula errors) in Column G of the 'Roadmap' sheet related to table lookups using "defined name" data ranges. 

For example, if I unhide column G, in cell G18 I see a lookup using 'AnsYTBL' which is mapped to a data range on the hidden 'Lookups' sheet. This appears to be the wrong lookup for the available answers of Governance->Strategy&Metric->Create and Promote->Level 1. As a result, when the answer is set to a non-zero response on the 'Interview tab, it is coded as a zero response on the roadmap. Screenshots attached.

This does not appear to be the case with the spreadsheet referenced by @SebaDele: https://github.com/owaspsamm/toolbox-spreadsheet/blob/main/resources/SAMM_spreadsheet.xlsx. 

Is there an issue where the most recent Excel spreadsheet is not actually included in the v2.1.0 release? The problematic spreadsheet is marked as version "2.0" whereas the one referenced by @SebaDele is marked as version "2.0.10".

![Image](https://github.com/user-attachments/assets/1ebf2c2c-59c5-478e-bec0-1e8fc0ebbdea)
![Image](https://github.com/user-attachments/assets/ffb1a44e-89e3-43f4-a76c-d76c51f76b87)
![Image](https://github.com/user-attachments/assets/bcf7c87a-7253-4d28-ae0c-37f4c25e541b)
