### ISSUE TITLE
Interview option that should be reviewed/changed

### ISSUE THREAD

**Issue by Pat-Duarte** [owaspsamm/core#23]
Hi,
in SAMM_Assessment_Toolbox_v2.0.xlsx,, for line 194 "Do you review and update the incident detection process regularly?"
the following answer options don't seem correct: Yes, for some applications, etc

In Data Validity, F194 is AnsF . AnsT seems more appropriate, so the options will be
No
Yes, but we improve it ad-hoc
Yes, we improve it at regular times
Yes, we improve it at least annually

History in old repo:
@kostasadriano opened this issue on Mar 20, 2020
@23bartman assigned @johndileo on Dec 23, 2020

**Comment by dkefer** [comment]
I don't think AnsT would be appropriate as the "quality criteria" says explicitly "you perform reviews at least annually".

**Comment by dkefer** [comment]
Btw. I've double checked that the mapping is done according to core/model/questions/O-IM-3-A.yml (answer set model/answer_sets/A.yml is referenced there), so it's not primarily a spreadsheet issue, assuming it's an issue.

**Comment by SebaDele** [comment]
to be discussed it this really is a answer set mismatch or not ...

**Comment by 23bartman** [comment]
This has been fixed.
