### ISSUE TITLE
Two questions have the same ID

### ISSUE THREAD

**Issue by Pat-Duarte** [owaspsamm/core#24]
Hi,
The following two questions have the same ID (1e005e11997f4929a12fdb939599e77e):
samm/Supporting Resources/v2.0/Datamodel/Datafiles/Question O-EM-1-A.yml
samm/Supporting Resources/v2.0/Datamodel/Datafiles/Question O-IM-1-A.yml

This has to be a mistake right?
It causes some trouble if one needs to parse the content.

Old repo history:
@dschwarz91 opened this issue on May 14, 2020
@fzipi fzipi added the bug label on Nov 14, 2020
@23bartman 23bartman self-assigned this on Dec 23, 2020

**Comment by aramhovsepyan** [comment]
+1

**Comment by 23bartman** [comment]
This issue does no longer exist in the current repo. The ID of IM-1-A has changed in the meantime.
