### ISSUE TITLE
A number of small typos to fix

### ISSUE THREAD

**Issue by Pat-Duarte** [owaspsamm/core#26]
I noticed a number of minor typos while reading through the text but don't have a git environment at hand to directly fix them, hence this issue to track them.

SR1 Activity
The security competences and habits of the expernal suppliers..

https://owaspsamm.org/v1-5/
While we recommend to use the latest version of SAMM, here are is the version 1.5:

SA
Technology management looks at the .. (capitalise management to match stream name)
Add missing periods at the end of the short descriptions for Stream A1, Stream B2

AD1
the team considers each principle in the context of the overall system and identify features

AD2
standardize on one or more shared service per category

TM1 quality criteria
You have a list of the most important technologies used in or in support of each application (add commas)

History from old repo:

@nessimk opened this issue on Jun 2, 2020
@nessimk self-assigned this on Jun 2, 2020

**Comment by RossBarnie** [comment]
I believe this can be closed since #71 got merged to develop.

**Comment by dkefer** [comment]
This issue remained open by mistake, closing now!
