### ISSUE TITLE
Roadmap Phase 3 implimentation questions have wrong data validation rules

### ISSUE THREAD

**Issue by Pat-Duarte** [owaspsamm/core#28]
The data validation is set to use "AnsD" for the list source of choices, but it should be "AnsF" This is breaking the roadmap in that section as a result (since it isn't the right answer and isn't scored appropriately). This is in Column R on the "Roadmap" tab.

History in old repo:
@rhitmojo opened this issue on Jul 30, 2020
@23bartman commented on Dec 23, 2020
Many thanks for your feedback. We will look into this.
@23bartman 23bartman assigned dkefer on Dec 23, 2020

**Comment by dkefer** [comment]
This seems to have been fixed already, closing here.
