### ISSUE TITLE
Type error in related activities on Datafiles/Activity V-AA-1-A.yml

### ISSUE THREAD

**Issue by Pat-Duarte** [owaspsamm/core#32]
There is a problem with

samm/Supporting Resources/v2.0/Datamodel/Datafiles/Activity V-AA-1-A.yml

Line 50 in 7ff7b3a

   - Security Requirements 
Data type should be a list of activities ID, not a string.

History from old repo:

@fzipi opened this issue on Nov 14, 2020
@fzipi added the bug label on Nov 14, 2020
@23bartman self-assigned this on Dec 23, 2020

**Comment by dkefer** [comment]
Has already been fixed with https://github.com/owaspsamm/core/commit/35a87e6621840bb7f72f4b3d474f9a6e0facd286.
