### ISSUE TITLE
Improve phrasing in EG3B

### ISSUE THREAD

**Issue by Pat-Duarte** [owaspsamm/core#36]
Replace this:
Form communities around roles and responsibilities and enable developers and engineers from different teams and business units to communicate freely and benefit from each other’s expertise.

With this:
Form communities around roles and responsibilities. Enable developers and engineers from different teams and business units to communicate freely so they can benefit from each other’s expertise.

**History from old repo:**
@Pat-Duarte opened this issue on Mar 20
@Pat-Duarte Pat-Duarte assigned 23bartman on Mar 20

**Comment by johnellingsworth** [comment]
Linking to #53
