### ISSUE TITLE
Operations - Incident Detection

### ISSUE THREAD

**Issue by Pat-Duarte** [owaspsamm/core#38]
We should consider incorporating:
Application instrumentation as the means for identifying active attacks, abuse of specific application functionality, and other abnormal application behavior.

Example: Business Logic abuse such as a peak of a specific functionality over time.

This is a real-time monitoring requirement.

Level 2 or 3 (likely 3)

**History from old repo:**
@yanfosec opened this issue on Jun 6, 2018
@23bartman assigned johndileo on Dec 23, 2020

**Comment by 23bartman** [comment]
We will look into this when looking into issue samm-suite #72 (support telemetry).
