### ISSUE TITLE
Support for not applicable in scoring

### ISSUE THREAD

**Issue by Pat-Duarte** [owaspsamm/core#56]
Investigate how we could support not/applicable situations for companies in the scoring system

**History from old repo:**
@23bartman opened this issue on Nov 24, 2019
@23bartman added the enhancement label on Nov 24, 2019
@23bartman assigned SebaDele, 23bartman, yanfosec and infosecdad on Nov 24, 2019
@23bartman commented on Nov 24, 2019
To be looked into for v2.1

**Comment by 23bartman** [comment]
This has been discussed in a blogpost: https://owaspsamm.org/blog/2023/02/28/the-not-applicable-question/
