### ISSUE TITLE
"Threat Assessment" yaml files have a space instead of a dash

### ISSUE THREAD

**Issue by Pat-Duarte** [owaspsamm/core#62]
# I expect
all yaml Datafiles having a consistent name, eg:
```
Practice D-Security-Architecture.yml
Practice D-Security-Requirements.yml
```
# Instead
Assessment files do not respect that (they have one more space instead of dash)
```
Practice D-Threat Assessment.yml
Practice V-Architecture Assessment.yml
```

**History from old repo:**
@ioggstream opened this issue on Apr 14, 2021
@23bartman assigned 23bartman and unassigned 23bartman 22 days ago

**Comment by 23bartman** [comment]
Impact needs to be checked by regenerating the website with the fix.

**Comment by dkefer** [comment]
Trivial change, but as more thorough testing is needed for v2.1, we should leverage this synergy.
