### ISSUE TITLE
Enhancements to the model

### ISSUE THREAD

**Issue by 23bartman** [owaspsamm/core#83]
We should think about:
- development environments
- test data
- ...

**Comment by SebaDele** [comment]
good intent, but better content will make this better building block(s).
merge with other 3.0 candidate improvements?
to be made more specific and actionable?
possibly move to a potential list of improvements that includes more detail?

**Comment by 23bartman** [comment]
This is covered in issue #81 in Samm-suite (on DTAP environments).
