### ISSUE TITLE
typo - Secure Deployment - Stream A

### ISSUE THREAD

**Issue by SebaDele** [owaspsamm/core#94]
There’s a spelling mistake in https://owaspsamm.org/model/implementation/secure-deployment/:
“indenendently” should be “independently”.

raised by email to info mailbox

**Comment by Pat-Duarte** [comment]
Looks like this was fixed.
![image](https://github.com/owaspsamm/core/assets/41348252/4fca9181-aeaa-4bc0-b5e0-e14ab59e370e)
